import path from "node:path";
import { fileURLToPath } from "node:url";

import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "happy-dom",
    setupFiles: ["./tests/setup.ts"],
    isolate: true,
    fileParallelism: false,
    pool: "forks",
    poolOptions: {
      forks: {
        singleFork: true,
      },
    },
    coverage: {
      provider: "v8",
      include: [
        "lib/api/employees.ts",
        "lib/api/employee-import.ts",
        "lib/api/compensation-import.ts",
        "lib/api/analytics.ts",
        "lib/api/ai-insights.ts",
        "lib/api/client.ts",
        "lib/format-salary.ts",
        "lib/format-display-salary.ts",
        "lib/hooks/use-exchange-rates.ts",
        "lib/analytics/fetch-analytics-dashboard.ts",
        "lib/hooks/use-debounced-value.ts",
        "lib/hooks/use-employee-directory.ts",
        "lib/hooks/use-employee-import.ts",
        "lib/hooks/use-compensation-import.ts",
        "lib/hooks/use-analytics-dashboard.ts",
        "lib/hooks/use-display-currency.ts",
        "lib/hooks/display-currency-provider.tsx",
        "lib/hooks/use-insight-query-parser.ts",
        "components/employee-directory/employee-directory.tsx",
        "components/employee-directory/employee-directory-filters.tsx",
        "components/employee-directory/employee-directory-table.tsx",
        "components/employee-directory/employee-directory-mobile-filters.tsx",
        "components/employee-directory/column-filter-popover.tsx",
        "components/employee-directory/employee-row.tsx",
        "components/employee-import/employee-import.tsx",
        "components/employee-import/employee-import-preview.tsx",
        "components/compensation-import/compensation-import.tsx",
        "components/compensation-import/compensation-import-preview.tsx",
        "components/analytics/analytics-dashboard.tsx",
        "components/analytics/analytics-kpi-cards.tsx",
        "components/analytics/analytics-department-payroll-section.tsx",
        "components/analytics/analytics-top-earners-list.tsx",
        "components/ai-insights/insight-query-panel.tsx",
        "components/ai-insights/parsed-insight-summary.tsx",
        "components/ai-insights/insight-execution-result.tsx",
        "components/layout/display-currency-selector.tsx",
        "components/layout/app-shell.tsx",
        "components/layout/site-header.tsx",
        "components/employee-profile/employee-profile.tsx",
        "components/employee-profile/employee-profile.tsx",
        "components/employee-profile/employee-profile-summary.tsx",
        "components/employee-profile/employee-current-compensation.tsx",
        "components/employee-profile/compensation-timeline.tsx",
        "components/employee-profile/record-compensation-change-form.tsx",
        "lib/hooks/use-employee-profile.ts",
      ],
      thresholds: {
        lines: 95,
        functions: 95,
        branches: 95,
        statements: 95,
      },
    },
  },
  resolve: {
    alias: {
      "@": path.resolve(path.dirname(fileURLToPath(import.meta.url)), "."),
    },
  },
});
